[customizations.installer.kickstart]
contents = """
text --non-interactive
zerombr
clearpart --all --initlabel --disklabel=gpt
autopart --noswap --type=plain
network --bootproto=dhcp --device=link --activate --onboot=on
rootpw --plaintext kiosk

%post
systemctl set-default graphical.target

cat > /boot/grub2/custom.cfg <<'EOF'
set timeout=0
set timeout_style=hidden
EOF
%end
"""
